// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/cert/v1beta3/genesis.proto

package v1beta3

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisCertificate defines certificate entry at genesis
type GenesisCertificate struct {
	Owner       string      `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner" yaml:"owner"`
	Certificate Certificate `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate" yaml:"certificate"`
}

func (m *GenesisCertificate) Reset()         { *m = GenesisCertificate{} }
func (m *GenesisCertificate) String() string { return proto.CompactTextString(m) }
func (*GenesisCertificate) ProtoMessage()    {}
func (*GenesisCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9698bf259a960a0, []int{0}
}
func (m *GenesisCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisCertificate.Merge(m, src)
}
func (m *GenesisCertificate) XXX_Size() int {
	return m.Size()
}
func (m *GenesisCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisCertificate proto.InternalMessageInfo

func (m *GenesisCertificate) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisCertificate) GetCertificate() Certificate {
	if m != nil {
		return m.Certificate
	}
	return Certificate{}
}

// GenesisState defines the basic genesis state used by cert module
type GenesisState struct {
	Certificates GenesisCertificates `protobuf:"bytes,1,rep,name=certificates,proto3,castrepeated=GenesisCertificates" json:"certificates" yaml:"certificates"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9698bf259a960a0, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetCertificates() GenesisCertificates {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisCertificate)(nil), "akash.cert.v1beta3.GenesisCertificate")
	proto.RegisterType((*GenesisState)(nil), "akash.cert.v1beta3.GenesisState")
}

func init() { proto.RegisterFile("akash/cert/v1beta3/genesis.proto", fileDescriptor_b9698bf259a960a0) }

var fileDescriptor_b9698bf259a960a0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0x3a, 0x31,
	0x18, 0xc6, 0xaf, 0xff, 0x7f, 0x34, 0xb1, 0x30, 0x15, 0x07, 0x24, 0xb1, 0xbd, 0x74, 0x30, 0x38,
	0xd0, 0x46, 0x98, 0x74, 0x3c, 0x13, 0xdd, 0x61, 0x73, 0x2b, 0x47, 0x39, 0x2e, 0xc0, 0x95, 0xb4,
	0x55, 0xe3, 0x97, 0x30, 0x7e, 0x03, 0x77, 0x57, 0xbf, 0x04, 0x23, 0xa3, 0x53, 0x35, 0xb0, 0x31,
	0xf2, 0x09, 0x0c, 0x3d, 0x12, 0x8f, 0x1c, 0xdb, 0xdb, 0x27, 0xcf, 0xf3, 0xbc, 0xbf, 0xe6, 0x85,
	0xa1, 0x18, 0x0b, 0x33, 0xe2, 0xb1, 0xd4, 0x96, 0x3f, 0x5d, 0xf5, 0xa5, 0x15, 0x1d, 0x9e, 0xc8,
	0x4c, 0x9a, 0xd4, 0xb0, 0x99, 0x56, 0x56, 0x21, 0xe4, 0x1d, 0x6c, 0xeb, 0x60, 0x3b, 0x47, 0xe3,
	0xfc, 0x40, 0xca, 0x1b, 0x7c, 0xa4, 0x71, 0x9a, 0xa8, 0x44, 0xf9, 0x91, 0x6f, 0xa7, 0x5c, 0xa5,
	0x9f, 0x00, 0xa2, 0xfb, 0xbc, 0xfa, 0x56, 0x6a, 0x9b, 0x0e, 0xd3, 0x58, 0x58, 0x89, 0x38, 0x3c,
	0x52, 0xcf, 0x99, 0xd4, 0x75, 0x10, 0x82, 0xe6, 0x49, 0x74, 0xb6, 0x76, 0x24, 0x17, 0x36, 0x8e,
	0x54, 0x5f, 0xc4, 0x74, 0x72, 0x43, 0xfd, 0x93, 0x76, 0x73, 0x19, 0x4d, 0x60, 0x25, 0xfe, 0xcb,
	0xd7, 0xff, 0x85, 0xa0, 0x59, 0x69, 0x13, 0x56, 0xc6, 0x64, 0x85, 0x35, 0xd1, 0xe5, 0xdc, 0x91,
	0x60, 0xed, 0x48, 0x31, 0xbb, 0x71, 0x04, 0xe5, 0x1b, 0x0a, 0x22, 0xed, 0x16, 0x2d, 0xf4, 0x1d,
	0xc0, 0xea, 0x8e, 0xba, 0x67, 0xb7, 0xbc, 0xaf, 0x00, 0x56, 0x0b, 0x06, 0x53, 0x07, 0xe1, 0xff,
	0x66, 0xa5, 0x7d, 0x71, 0x08, 0xa0, 0xfc, 0xdd, 0x28, 0xda, 0x71, 0xec, 0x75, 0x6c, 0x1c, 0xa9,
	0x95, 0x40, 0x0c, 0xfd, 0xf8, 0x26, 0xb5, 0x72, 0x85, 0xe9, 0xee, 0x65, 0xa3, 0xde, 0x7c, 0x89,
	0xc1, 0x62, 0x89, 0xc1, 0xcf, 0x12, 0x83, 0xb7, 0x15, 0x0e, 0x16, 0x2b, 0x1c, 0x7c, 0xad, 0x70,
	0xf0, 0x70, 0x9d, 0xa4, 0x76, 0xf4, 0xd8, 0x67, 0xb1, 0x9a, 0x72, 0x33, 0x1b, 0x49, 0xad, 0xb2,
	0xbb, 0x41, 0xc6, 0x3d, 0x68, 0x4b, 0xcc, 0xd2, 0xd6, 0x50, 0xe9, 0x31, 0x4f, 0x14, 0xcf, 0xd4,
	0x40, 0xee, 0x5d, 0xb3, 0x7f, 0xec, 0x6f, 0xd6, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x83,
	0xd4, 0x17, 0x20, 0x02, 0x00, 0x00,
}

func (m *GenesisCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Certificate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Certificates) > 0 {
		for iNdEx := len(m.Certificates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Certificates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Certificate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Certificates) > 0 {
		for _, e := range m.Certificates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Certificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Certificates = append(m.Certificates, GenesisCertificate{})
			if err := m.Certificates[len(m.Certificates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
