// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/gov/v1beta3/params.proto

package v1beta3

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DepositParams defines the parameters for the x/gov module
type DepositParams struct {
	// min_initial_deposit_rate minimum % of TotalDeposit
	// author of the proposal must put in order for proposal tx to be committed
	MinInitialDepositRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=min_initial_deposit_rate,json=minInitialDepositRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_initial_deposit_rate" yaml:"min_initial_deposit_rate"`
}

func (m *DepositParams) Reset()         { *m = DepositParams{} }
func (m *DepositParams) String() string { return proto.CompactTextString(m) }
func (*DepositParams) ProtoMessage()    {}
func (*DepositParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7c87bcce7fe71f, []int{0}
}
func (m *DepositParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DepositParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DepositParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DepositParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositParams.Merge(m, src)
}
func (m *DepositParams) XXX_Size() int {
	return m.Size()
}
func (m *DepositParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositParams.DiscardUnknown(m)
}

var xxx_messageInfo_DepositParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DepositParams)(nil), "akash.gov.v1beta3.DepositParams")
}

func init() { proto.RegisterFile("akash/gov/v1beta3/params.proto", fileDescriptor_ff7c87bcce7fe71f) }

var fileDescriptor_ff7c87bcce7fe71f = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x9b, 0xc5, 0xa1, 0xe8, 0xe0, 0xe1, 0xc1, 0xe1, 0x90, 0x48, 0x07, 0x71, 0x69, 0x83,
	0xdc, 0x22, 0x8e, 0xc7, 0x21, 0x38, 0x08, 0xd2, 0xd1, 0xa5, 0xa4, 0x6d, 0x4c, 0x43, 0x2f, 0xf9,
	0x42, 0x13, 0x0b, 0xf7, 0x07, 0x9c, 0xfd, 0x49, 0x8e, 0x37, 0x1e, 0x4e, 0xe2, 0x50, 0xa4, 0xdd,
	0x1c, 0xfd, 0x05, 0x62, 0xdb, 0xe1, 0x86, 0xbb, 0x29, 0x81, 0xe7, 0xe5, 0x7d, 0x3f, 0x1e, 0x1f,
	0xb3, 0x92, 0xd9, 0x82, 0x0a, 0xa8, 0x69, 0x7d, 0x9d, 0x72, 0xc7, 0xe6, 0xd4, 0xb0, 0x8a, 0x29,
	0x1b, 0x99, 0x0a, 0x1c, 0x4c, 0x4e, 0x7b, 0x1e, 0x09, 0xa8, 0xa3, 0x91, 0x9f, 0x9f, 0x09, 0x10,
	0xd0, 0x53, 0xfa, 0xff, 0x1b, 0x82, 0xc1, 0x07, 0xf2, 0x4f, 0x96, 0xdc, 0x80, 0x95, 0xee, 0xb1,
	0x2f, 0x98, 0xbc, 0x23, 0x7f, 0xa6, 0xa4, 0x4e, 0xa4, 0x96, 0x4e, 0xb2, 0x55, 0x92, 0x0f, 0x34,
	0xa9, 0x98, 0xe3, 0x33, 0x74, 0x81, 0xae, 0x8e, 0x17, 0xaf, 0x68, 0xd3, 0x10, 0xef, 0xab, 0x21,
	0x97, 0x42, 0xba, 0xe2, 0x25, 0x8d, 0x32, 0x50, 0x34, 0x03, 0xab, 0xc0, 0x8e, 0x4f, 0x68, 0xf3,
	0x92, 0xba, 0xb5, 0xe1, 0x36, 0x5a, 0xf2, 0xac, 0x6d, 0xc8, 0xf4, 0x41, 0xea, 0xfb, 0xa1, 0x71,
	0x9c, 0x8b, 0x99, 0xe3, 0x3f, 0x0d, 0x39, 0xb8, 0xf5, 0xdb, 0x10, 0xb2, 0x66, 0x6a, 0x75, 0x1b,
	0x1c, 0x4a, 0x04, 0xf1, 0x54, 0xed, 0x6b, 0x5d, 0xc4, 0x9b, 0x16, 0xa3, 0x6d, 0x8b, 0xd1, 0x77,
	0x8b, 0xd1, 0x5b, 0x87, 0xbd, 0x6d, 0x87, 0xbd, 0xcf, 0x0e, 0x7b, 0x4f, 0x37, 0x3b, 0x07, 0x5b,
	0x53, 0xf0, 0x0a, 0xf4, 0x5d, 0xae, 0x69, 0x6f, 0x2b, 0x64, 0x46, 0x86, 0xcf, 0x50, 0x95, 0x54,
	0x00, 0xd5, 0x90, 0xf3, 0x5d, 0xbd, 0xe9, 0x51, 0xef, 0x6b, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x4d, 0x18, 0xa1, 0x7a, 0x01, 0x00, 0x00,
}

func (m *DepositParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DepositParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DepositParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinInitialDepositRate.Size()
		i -= size
		if _, err := m.MinInitialDepositRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DepositParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinInitialDepositRate.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DepositParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DepositParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DepositParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInitialDepositRate", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinInitialDepositRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
