// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/gpu.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GPUInfo reports GPU details
type GPUInfo struct {
	Vendor     string `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor" yaml:"vendor"`
	VendorID   string `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id" yaml:"vendor_id"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name" yaml:"name"`
	ModelID    string `protobuf:"bytes,4,opt,name=modelid,proto3" json:"model_id" yaml:"model_id"`
	Interface  string `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface" yaml:"interface"`
	MemorySize string `protobuf:"bytes,6,opt,name=memory_size,json=memorySize,proto3" json:"memory_size" yaml:"memory_size"`
}

func (m *GPUInfo) Reset()         { *m = GPUInfo{} }
func (m *GPUInfo) String() string { return proto.CompactTextString(m) }
func (*GPUInfo) ProtoMessage()    {}
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc01b12bd00ffcc, []int{0}
}
func (m *GPUInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GPUInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GPUInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GPUInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUInfo.Merge(m, src)
}
func (m *GPUInfo) XXX_Size() int {
	return m.Size()
}
func (m *GPUInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GPUInfo proto.InternalMessageInfo

func (m *GPUInfo) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *GPUInfo) GetVendorID() string {
	if m != nil {
		return m.VendorID
	}
	return ""
}

func (m *GPUInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPUInfo) GetModelID() string {
	if m != nil {
		return m.ModelID
	}
	return ""
}

func (m *GPUInfo) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *GPUInfo) GetMemorySize() string {
	if m != nil {
		return m.MemorySize
	}
	return ""
}

// GPUInfo reports GPU inventory details
type GPU struct {
	Quantity ResourcePair `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity" yaml:"quantity"`
	Info     GPUInfoS     `protobuf:"bytes,2,rep,name=info,proto3,castrepeated=GPUInfoS" json:"info" yaml:"info"`
}

func (m *GPU) Reset()         { *m = GPU{} }
func (m *GPU) String() string { return proto.CompactTextString(m) }
func (*GPU) ProtoMessage()    {}
func (*GPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc01b12bd00ffcc, []int{1}
}
func (m *GPU) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GPU.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPU.Merge(m, src)
}
func (m *GPU) XXX_Size() int {
	return m.Size()
}
func (m *GPU) XXX_DiscardUnknown() {
	xxx_messageInfo_GPU.DiscardUnknown(m)
}

var xxx_messageInfo_GPU proto.InternalMessageInfo

func (m *GPU) GetQuantity() ResourcePair {
	if m != nil {
		return m.Quantity
	}
	return ResourcePair{}
}

func (m *GPU) GetInfo() GPUInfoS {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*GPUInfo)(nil), "akash.inventory.v1.GPUInfo")
	proto.RegisterType((*GPU)(nil), "akash.inventory.v1.GPU")
}

func init() { proto.RegisterFile("akash/inventory/v1/gpu.proto", fileDescriptor_2cc01b12bd00ffcc) }

var fileDescriptor_2cc01b12bd00ffcc = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x6e, 0xd3, 0x30,
	0x18, 0x6f, 0xd6, 0xd2, 0xb5, 0xae, 0x10, 0xc8, 0xe2, 0x10, 0x0d, 0x14, 0x57, 0x96, 0x26, 0x4d,
	0x48, 0x4d, 0xb4, 0x95, 0x13, 0x12, 0x97, 0x6a, 0x62, 0x2a, 0x62, 0x53, 0xc9, 0x18, 0x07, 0x2e,
	0xc5, 0x6b, 0xdc, 0xd4, 0xda, 0x62, 0x07, 0x37, 0xad, 0xd4, 0x3d, 0x05, 0xcf, 0xc1, 0x95, 0x97,
	0xd8, 0x71, 0x27, 0xc4, 0xc9, 0xa0, 0xf4, 0xd6, 0x63, 0x9f, 0x00, 0xd9, 0xf9, 0x37, 0xc4, 0x6e,
	0xfe, 0x7e, 0xff, 0x3e, 0xdb, 0xdf, 0x07, 0x5e, 0x90, 0x2b, 0x32, 0x9f, 0x79, 0x8c, 0x2f, 0x29,
	0x4f, 0x84, 0x5c, 0x79, 0xcb, 0x43, 0x2f, 0x8c, 0x17, 0x6e, 0x2c, 0x45, 0x22, 0x20, 0x34, 0xac,
	0x5b, 0xb2, 0xee, 0xf2, 0x70, 0xef, 0x59, 0x28, 0x42, 0x61, 0x68, 0x4f, 0x9f, 0x32, 0xe5, 0xde,
	0xfe, 0x03, 0x39, 0x92, 0xce, 0xc5, 0x42, 0x4e, 0x68, 0x4c, 0x98, 0xcc, 0x64, 0xf8, 0x47, 0x1d,
	0xec, 0x9e, 0x8c, 0x2e, 0x86, 0x7c, 0x2a, 0xe0, 0x1b, 0xd0, 0x5c, 0x52, 0x1e, 0x08, 0x69, 0x5b,
	0x5d, 0xeb, 0xa0, 0x3d, 0xd8, 0x4f, 0x15, 0x6a, 0x7e, 0x32, 0xc8, 0x46, 0xa1, 0x9c, 0xdb, 0x2a,
	0xf4, 0x78, 0x45, 0xa2, 0xeb, 0xd7, 0x38, 0xab, 0xb1, 0x9f, 0x13, 0xf0, 0x1d, 0x68, 0x67, 0xa7,
	0x31, 0x0b, 0xec, 0x1d, 0x93, 0xd0, 0x4b, 0x15, 0x6a, 0x65, 0x09, 0xc3, 0xe3, 0x8d, 0x42, 0x95,
	0x60, 0xab, 0xd0, 0xd3, 0xfb, 0x31, 0x63, 0x16, 0x60, 0xbf, 0x95, 0x9d, 0x87, 0x01, 0xec, 0x83,
	0x06, 0x27, 0x11, 0xb5, 0xeb, 0x26, 0x06, 0xa5, 0x0a, 0x35, 0xce, 0x48, 0x44, 0x37, 0x0a, 0x19,
	0x7c, 0xab, 0x50, 0x27, 0x73, 0xeb, 0x0a, 0xfb, 0x06, 0x84, 0xc7, 0x60, 0x37, 0x12, 0x01, 0xbd,
	0x66, 0x81, 0xdd, 0x30, 0xbe, 0x97, 0xa9, 0x42, 0xbb, 0xa7, 0x1a, 0x32, 0xdd, 0x5b, 0x86, 0xcd,
	0x9a, 0x3f, 0xc9, 0xec, 0x05, 0x82, 0xfd, 0xc2, 0x0a, 0xdf, 0x83, 0x36, 0xe3, 0x09, 0x95, 0x53,
	0x32, 0xa1, 0xf6, 0x23, 0x93, 0xe3, 0xa6, 0x0a, 0xb5, 0x87, 0x05, 0xa8, 0xdf, 0x51, 0x2a, 0xaa,
	0x77, 0x94, 0x10, 0xf6, 0x2b, 0x1a, 0x7e, 0x04, 0x9d, 0x88, 0x46, 0x42, 0xae, 0xc6, 0x73, 0x76,
	0x43, 0xed, 0xa6, 0xc9, 0xeb, 0xa7, 0x0a, 0x81, 0x53, 0x03, 0x9f, 0xb3, 0x1b, 0x1d, 0x78, 0x5f,
	0xb4, 0x55, 0x08, 0xe6, 0xb7, 0xab, 0x40, 0xec, 0x83, 0xa8, 0x34, 0xe0, 0x9f, 0x16, 0xa8, 0x9f,
	0x8c, 0x2e, 0x60, 0x04, 0x5a, 0x5f, 0x17, 0x84, 0x27, 0x2c, 0x59, 0x99, 0x99, 0x75, 0x8e, 0xba,
	0xee, 0xff, 0x1b, 0xe2, 0xfa, 0xf9, 0xdc, 0x47, 0x84, 0xc9, 0x81, 0x77, 0xab, 0x50, 0x4d, 0xcf,
	0xe5, 0x43, 0xee, 0xd4, 0x3f, 0x53, 0xa4, 0x54, 0x3f, 0x53, 0x20, 0xd8, 0x2f, 0x49, 0xf8, 0x05,
	0x34, 0x18, 0x9f, 0x0a, 0x7b, 0xa7, 0x5b, 0x3f, 0xe8, 0x1c, 0x3d, 0x7f, 0xa8, 0x55, 0xbe, 0x4b,
	0x65, 0x97, 0x86, 0xae, 0xf4, 0xd8, 0xb4, 0xb1, 0x1a, 0x9b, 0xae, 0xf0, 0xf7, 0xdf, 0xa8, 0x95,
	0xeb, 0xcf, 0x7d, 0x23, 0x18, 0x9c, 0xdd, 0xa6, 0x8e, 0x75, 0x97, 0x3a, 0xd6, 0x9f, 0xd4, 0xb1,
	0xbe, 0xad, 0x9d, 0xda, 0xdd, 0xda, 0xa9, 0xfd, 0x5a, 0x3b, 0xb5, 0xcf, 0xaf, 0x42, 0x96, 0xcc,
	0x16, 0x97, 0xee, 0x44, 0x44, 0xde, 0x3c, 0x9e, 0x51, 0x29, 0xf8, 0xdb, 0x80, 0x7b, 0xe6, 0x0a,
	0x3d, 0x12, 0xb3, 0xde, 0x54, 0xc8, 0x2b, 0x2f, 0x14, 0xff, 0x6c, 0xfc, 0x65, 0xd3, 0x6c, 0x79,
	0xff, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x51, 0x58, 0xf7, 0x56, 0x03, 0x00, 0x00,
}

func (m *GPUInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GPUInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GPUInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MemorySize) > 0 {
		i -= len(m.MemorySize)
		copy(dAtA[i:], m.MemorySize)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.MemorySize)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Interface) > 0 {
		i -= len(m.Interface)
		copy(dAtA[i:], m.Interface)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.Interface)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ModelID) > 0 {
		i -= len(m.ModelID)
		copy(dAtA[i:], m.ModelID)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.ModelID)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.VendorID) > 0 {
		i -= len(m.VendorID)
		copy(dAtA[i:], m.VendorID)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.VendorID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vendor) > 0 {
		i -= len(m.Vendor)
		copy(dAtA[i:], m.Vendor)
		i = encodeVarintGpu(dAtA, i, uint64(len(m.Vendor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GPU) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GPU) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GPU) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		for iNdEx := len(m.Info) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Info[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGpu(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Quantity.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGpu(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGpu(dAtA []byte, offset int, v uint64) int {
	offset -= sovGpu(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GPUInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Vendor)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	l = len(m.VendorID)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	l = len(m.ModelID)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	l = len(m.Interface)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	l = len(m.MemorySize)
	if l > 0 {
		n += 1 + l + sovGpu(uint64(l))
	}
	return n
}

func (m *GPU) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Quantity.Size()
	n += 1 + l + sovGpu(uint64(l))
	if len(m.Info) > 0 {
		for _, e := range m.Info {
			l = e.Size()
			n += 1 + l + sovGpu(uint64(l))
		}
	}
	return n
}

func sovGpu(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGpu(x uint64) (n int) {
	return sovGpu(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GPUInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGpu
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GPUInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GPUInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vendor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vendor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VendorID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VendorID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Interface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemorySize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemorySize = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGpu(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGpu
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GPU) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGpu
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GPU: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GPU: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGpu
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGpu
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = append(m.Info, GPUInfo{})
			if err := m.Info[len(m.Info)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGpu(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGpu
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGpu(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGpu
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGpu
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGpu
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGpu
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGpu
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGpu        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGpu          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGpu = fmt.Errorf("proto: unexpected end of group")
)
