// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/service.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("akash/inventory/v1/service.proto", fileDescriptor_19b1fad552cee5dc) }

var fileDescriptor_19b1fad552cee5dc = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x4a, 0x03, 0x31,
	0x14, 0xc6, 0x1b, 0x17, 0xfe, 0x09, 0x76, 0x13, 0x41, 0xca, 0x54, 0x83, 0x74, 0x29, 0x34, 0x69,
	0xab, 0x07, 0x10, 0x8b, 0x5d, 0x16, 0xad, 0x3b, 0xc1, 0x45, 0xa6, 0x4d, 0xa7, 0xa1, 0x6d, 0xde,
	0x90, 0xc9, 0x0c, 0x74, 0xeb, 0x09, 0x04, 0x0f, 0xe0, 0x21, 0xbc, 0x84, 0xcb, 0x82, 0x1b, 0x97,
	0xd2, 0x7a, 0x10, 0x49, 0x66, 0x5a, 0x10, 0xeb, 0x46, 0x97, 0xc9, 0xfb, 0xde, 0xef, 0xfb, 0x85,
	0xe0, 0x13, 0x31, 0x16, 0xc9, 0x88, 0x2b, 0x9d, 0x49, 0x6d, 0xc1, 0xcc, 0x78, 0xd6, 0xe4, 0x89,
	0x34, 0x99, 0xea, 0x4b, 0x16, 0x1b, 0xb0, 0x40, 0x88, 0x4f, 0xb0, 0x75, 0x82, 0x65, 0xcd, 0xa0,
	0x1a, 0x01, 0x44, 0x13, 0xc9, 0x7d, 0x22, 0x4c, 0x87, 0x5c, 0x4e, 0x63, 0x3b, 0xcb, 0x17, 0x82,
	0xa3, 0x62, 0x28, 0x62, 0xc5, 0x85, 0xd6, 0x60, 0x85, 0x55, 0xa0, 0x93, 0x62, 0x7a, 0xbc, 0xa1,
	0x50, 0xc3, 0xa0, 0x68, 0x0b, 0x36, 0xf9, 0xf4, 0x27, 0x69, 0x62, 0xa5, 0xc9, 0x13, 0xad, 0x67,
	0x84, 0x77, 0xba, 0x30, 0x90, 0xbd, 0xeb, 0x36, 0xe9, 0xe1, 0xbd, 0x9b, 0x54, 0x9a, 0x99, 0x3b,
	0x93, 0x43, 0x96, 0x17, 0xb3, 0x95, 0x15, 0xbb, 0x72, 0x56, 0x41, 0x85, 0xfd, 0x7c, 0x01, 0x73,
	0x1b, 0xb5, 0x83, 0x87, 0xb7, 0xcf, 0xa7, 0xad, 0x32, 0xd9, 0x5d, 0x49, 0x84, 0xe8, 0x94, 0x5c,
	0x60, 0x7c, 0x6b, 0x8d, 0x14, 0xd3, 0xbf, 0x41, 0x1b, 0xa8, 0xf5, 0x82, 0x30, 0x6e, 0xe7, 0xce,
	0x4e, 0xf2, 0x1e, 0xef, 0x7b, 0xc9, 0xe2, 0xea, 0x57, 0x64, 0x75, 0x13, 0xb2, 0x58, 0xaa, 0x55,
	0xbc, 0x2a, 0x21, 0x65, 0xa7, 0xba, 0x4e, 0x38, 0xdf, 0x0e, 0x2e, 0xe7, 0xbe, 0xff, 0xe1, 0x37,
	0xd0, 0x65, 0xf7, 0x75, 0x41, 0xd1, 0x7c, 0x41, 0xd1, 0xc7, 0x82, 0xa2, 0xc7, 0x25, 0x2d, 0xcd,
	0x97, 0xb4, 0xf4, 0xbe, 0xa4, 0xa5, 0xbb, 0xf3, 0x48, 0xd9, 0x51, 0x1a, 0xb2, 0x3e, 0x4c, 0x79,
	0x12, 0x8f, 0xa4, 0x01, 0xdd, 0x19, 0x68, 0xee, 0x69, 0x75, 0x11, 0xab, 0xfa, 0x10, 0xcc, 0x98,
	0x47, 0xf0, 0xed, 0xd7, 0xc2, 0x6d, 0x5f, 0x7f, 0xf6, 0x15, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x71,
	0x12, 0xbb, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeRPCClient is the client API for NodeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeRPCClient interface {
	// QueryNode defines a method to query hardware state of the node
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	QueryNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Node, error)
	// StreamNode defines a method to stream hardware state of the node
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NodeRPC_StreamNodeClient, error)
}

type nodeRPCClient struct {
	cc grpc1.ClientConn
}

func NewNodeRPCClient(cc grpc1.ClientConn) NodeRPCClient {
	return &nodeRPCClient{cc}
}

func (c *nodeRPCClient) QueryNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/akash.inventory.v1.NodeRPC/QueryNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) StreamNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NodeRPC_StreamNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[0], "/akash.inventory.v1.NodeRPC/StreamNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCStreamNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_StreamNodeClient interface {
	Recv() (*Node, error)
	grpc.ClientStream
}

type nodeRPCStreamNodeClient struct {
	grpc.ClientStream
}

func (x *nodeRPCStreamNodeClient) Recv() (*Node, error) {
	m := new(Node)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeRPCServer is the server API for NodeRPC service.
type NodeRPCServer interface {
	// QueryNode defines a method to query hardware state of the node
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	QueryNode(context.Context, *emptypb.Empty) (*Node, error)
	// StreamNode defines a method to stream hardware state of the node
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamNode(*emptypb.Empty, NodeRPC_StreamNodeServer) error
}

// UnimplementedNodeRPCServer can be embedded to have forward compatible implementations.
type UnimplementedNodeRPCServer struct {
}

func (*UnimplementedNodeRPCServer) QueryNode(ctx context.Context, req *emptypb.Empty) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNode not implemented")
}
func (*UnimplementedNodeRPCServer) StreamNode(req *emptypb.Empty, srv NodeRPC_StreamNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNode not implemented")
}

func RegisterNodeRPCServer(s grpc1.Server, srv NodeRPCServer) {
	s.RegisterService(&_NodeRPC_serviceDesc, srv)
}

func _NodeRPC_QueryNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).QueryNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.inventory.v1.NodeRPC/QueryNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).QueryNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_StreamNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).StreamNode(m, &nodeRPCStreamNodeServer{stream})
}

type NodeRPC_StreamNodeServer interface {
	Send(*Node) error
	grpc.ServerStream
}

type nodeRPCStreamNodeServer struct {
	grpc.ServerStream
}

func (x *nodeRPCStreamNodeServer) Send(m *Node) error {
	return x.ServerStream.SendMsg(m)
}

var _NodeRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "akash.inventory.v1.NodeRPC",
	HandlerType: (*NodeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryNode",
			Handler:    _NodeRPC_QueryNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNode",
			Handler:       _NodeRPC_StreamNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "akash/inventory/v1/service.proto",
}

// ClusterRPCClient is the client API for ClusterRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterRPCClient interface {
	// QueryCluster defines a method to query hardware state of the cluster
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	QueryCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Cluster, error)
	// StreamCluster defines a method to stream hardware state of the cluster
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ClusterRPC_StreamClusterClient, error)
}

type clusterRPCClient struct {
	cc grpc1.ClientConn
}

func NewClusterRPCClient(cc grpc1.ClientConn) ClusterRPCClient {
	return &clusterRPCClient{cc}
}

func (c *clusterRPCClient) QueryCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/akash.inventory.v1.ClusterRPC/QueryCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterRPCClient) StreamCluster(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ClusterRPC_StreamClusterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClusterRPC_serviceDesc.Streams[0], "/akash.inventory.v1.ClusterRPC/StreamCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterRPCStreamClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClusterRPC_StreamClusterClient interface {
	Recv() (*Cluster, error)
	grpc.ClientStream
}

type clusterRPCStreamClusterClient struct {
	grpc.ClientStream
}

func (x *clusterRPCStreamClusterClient) Recv() (*Cluster, error) {
	m := new(Cluster)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterRPCServer is the server API for ClusterRPC service.
type ClusterRPCServer interface {
	// QueryCluster defines a method to query hardware state of the cluster
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	QueryCluster(context.Context, *emptypb.Empty) (*Cluster, error)
	// StreamCluster defines a method to stream hardware state of the cluster
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamCluster(*emptypb.Empty, ClusterRPC_StreamClusterServer) error
}

// UnimplementedClusterRPCServer can be embedded to have forward compatible implementations.
type UnimplementedClusterRPCServer struct {
}

func (*UnimplementedClusterRPCServer) QueryCluster(ctx context.Context, req *emptypb.Empty) (*Cluster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCluster not implemented")
}
func (*UnimplementedClusterRPCServer) StreamCluster(req *emptypb.Empty, srv ClusterRPC_StreamClusterServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCluster not implemented")
}

func RegisterClusterRPCServer(s grpc1.Server, srv ClusterRPCServer) {
	s.RegisterService(&_ClusterRPC_serviceDesc, srv)
}

func _ClusterRPC_QueryCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterRPCServer).QueryCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/akash.inventory.v1.ClusterRPC/QueryCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterRPCServer).QueryCluster(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterRPC_StreamCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterRPCServer).StreamCluster(m, &clusterRPCStreamClusterServer{stream})
}

type ClusterRPC_StreamClusterServer interface {
	Send(*Cluster) error
	grpc.ServerStream
}

type clusterRPCStreamClusterServer struct {
	grpc.ServerStream
}

func (x *clusterRPCStreamClusterServer) Send(m *Cluster) error {
	return x.ServerStream.SendMsg(m)
}

var _ClusterRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "akash.inventory.v1.ClusterRPC",
	HandlerType: (*ClusterRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryCluster",
			Handler:    _ClusterRPC_QueryCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCluster",
			Handler:       _ClusterRPC_StreamCluster_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "akash/inventory/v1/service.proto",
}
