// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/deployment/v1beta3/groupspec.proto

package v1beta3

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1beta3 "github.com/spheronFdn/akash-api-fork/go/node/types/v1beta3"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GroupSpec stores group specifications
type GroupSpec struct {
	Name         string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	Requirements v1beta3.PlacementRequirements `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements" yaml:"requirements"`
	Resources    ResourceUnits                 `protobuf:"bytes,3,rep,name=resources,proto3,castrepeated=ResourceUnits" json:"resources" yaml:"resources"`
}

func (m *GroupSpec) Reset()         { *m = GroupSpec{} }
func (m *GroupSpec) String() string { return proto.CompactTextString(m) }
func (*GroupSpec) ProtoMessage()    {}
func (*GroupSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f47a9fa0e046026, []int{0}
}
func (m *GroupSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GroupSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GroupSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GroupSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSpec.Merge(m, src)
}
func (m *GroupSpec) XXX_Size() int {
	return m.Size()
}
func (m *GroupSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSpec.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GroupSpec)(nil), "akash.deployment.v1beta3.GroupSpec")
}

func init() {
	proto.RegisterFile("akash/deployment/v1beta3/groupspec.proto", fileDescriptor_8f47a9fa0e046026)
}

var fileDescriptor_8f47a9fa0e046026 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x93, 0xf6, 0xe3, 0xc3, 0xa6, 0x0a, 0x12, 0x05, 0x43, 0x17, 0x99, 0x92, 0x85, 0x44,
	0x4a, 0x67, 0xb0, 0x05, 0x17, 0xdd, 0x08, 0x59, 0xe8, 0x56, 0x22, 0x2e, 0x74, 0x37, 0x49, 0xc7,
	0x34, 0xb4, 0xc9, 0xc4, 0x99, 0x89, 0x50, 0xf1, 0x01, 0x5c, 0xfa, 0x08, 0x5d, 0xfb, 0x0c, 0x3e,
	0x40, 0x97, 0x5d, 0xba, 0x8a, 0xd2, 0x6e, 0xa4, 0xcb, 0x3e, 0x81, 0xe4, 0x4f, 0x6d, 0x0b, 0x76,
	0x37, 0xf7, 0xf2, 0xbb, 0xe7, 0xdc, 0x33, 0x57, 0x31, 0x71, 0x1f, 0xf3, 0x1e, 0xea, 0x92, 0x68,
	0x40, 0x87, 0x01, 0x09, 0x05, 0x7a, 0x3c, 0x75, 0x88, 0xc0, 0x6d, 0xe4, 0x31, 0x1a, 0x47, 0x3c,
	0x22, 0x2e, 0x8c, 0x18, 0x15, 0x54, 0xd5, 0x32, 0x12, 0xae, 0x48, 0x58, 0x90, 0xb5, 0x43, 0x8f,
	0x7a, 0x34, 0x83, 0x50, 0xfa, 0xca, 0xf9, 0x9a, 0x91, 0x2b, 0x3b, 0x98, 0x93, 0x5f, 0x4d, 0x2c,
	0x04, 0xf3, 0x9d, 0x58, 0x90, 0x82, 0x69, 0x6c, 0x75, 0x67, 0x84, 0xd3, 0x98, 0xb9, 0x24, 0x0e,
	0x7d, 0x91, 0xc3, 0xc6, 0x7b, 0x49, 0xa9, 0x5c, 0xa6, 0x4b, 0x5d, 0x47, 0xc4, 0x55, 0x1b, 0xca,
	0xbf, 0x10, 0x07, 0x44, 0x93, 0xeb, 0xb2, 0x59, 0xb1, 0x8e, 0xe6, 0x09, 0xc8, 0xea, 0x45, 0x02,
	0xaa, 0x43, 0x1c, 0x0c, 0x3a, 0x46, 0x5a, 0x19, 0x76, 0xd6, 0x54, 0x9f, 0x94, 0x5d, 0x46, 0x1e,
	0x62, 0x9f, 0x91, 0xd4, 0x84, 0x6b, 0xa5, 0xba, 0x6c, 0x56, 0x5b, 0x27, 0x30, 0x8f, 0x94, 0xae,
	0xb8, 0x0c, 0x03, 0xaf, 0x06, 0xd8, 0xcd, 0x28, 0x7b, 0x6d, 0xc0, 0x6a, 0x8c, 0x13, 0x20, 0xcd,
	0x13, 0xb0, 0x21, 0xb3, 0x48, 0xc0, 0x41, 0xee, 0xb5, 0xde, 0x35, 0xec, 0x0d, 0x48, 0x7d, 0x56,
	0x2a, 0xcb, 0x30, 0x5c, 0x2b, 0xd7, 0xcb, 0x66, 0xb5, 0x75, 0x0c, 0xb7, 0xfd, 0x25, 0xb4, 0x0b,
	0xf4, 0x26, 0xf4, 0x85, 0x75, 0x56, 0xb8, 0xae, 0x04, 0x16, 0x09, 0xd8, 0x5f, 0x5a, 0x16, 0x2d,
	0xe3, 0xed, 0x13, 0xec, 0xad, 0x8f, 0x71, 0x7b, 0xc5, 0x77, 0x76, 0x5e, 0x46, 0x40, 0xfa, 0x1e,
	0x01, 0xc9, 0xba, 0x1d, 0x4f, 0x75, 0x79, 0x32, 0xd5, 0xe5, 0xaf, 0xa9, 0x2e, 0xbf, 0xce, 0x74,
	0x69, 0x32, 0xd3, 0xa5, 0x8f, 0x99, 0x2e, 0xdd, 0x9d, 0x7b, 0xbe, 0xe8, 0xc5, 0x0e, 0x74, 0x69,
	0x80, 0x78, 0xd4, 0x23, 0x8c, 0x86, 0x17, 0xdd, 0x10, 0x65, 0x3b, 0x36, 0x71, 0xe4, 0x37, 0xef,
	0x29, 0xeb, 0x23, 0x8f, 0xa2, 0x90, 0x76, 0xc9, 0x1f, 0xc7, 0x72, 0xfe, 0x67, 0x07, 0x6a, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x35, 0xa0, 0x7e, 0xd2, 0x4d, 0x02, 0x00, 0x00,
}

func (m *GroupSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GroupSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Resources) > 0 {
		for iNdEx := len(m.Resources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Resources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGroupspec(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Requirements.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGroupspec(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGroupspec(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGroupspec(dAtA []byte, offset int, v uint64) int {
	offset -= sovGroupspec(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GroupSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGroupspec(uint64(l))
	}
	l = m.Requirements.Size()
	n += 1 + l + sovGroupspec(uint64(l))
	if len(m.Resources) > 0 {
		for _, e := range m.Resources {
			l = e.Size()
			n += 1 + l + sovGroupspec(uint64(l))
		}
	}
	return n
}

func sovGroupspec(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGroupspec(x uint64) (n int) {
	return sovGroupspec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GroupSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGroupspec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requirements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Requirements.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGroupspec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGroupspec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resources = append(m.Resources, ResourceUnit{})
			if err := m.Resources[len(m.Resources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGroupspec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGroupspec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGroupspec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGroupspec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGroupspec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGroupspec
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGroupspec
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGroupspec
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGroupspec        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGroupspec          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGroupspec = fmt.Errorf("proto: unexpected end of group")
)
